// Printable worksheet as a real PDF, generated in the browser from the same question generator.

import { jsPDF } from "jspdf";
import { components, type Launch } from "../../physics/projectile";
import { makeLaunch, makeQuestion, type Question, SKILLS } from "./questions";

export function worksheetQuestions(seed: number): Question[] {
  const out: Question[] = [];
  for (let i = 0; i < 6; i++) {
    const skill = SKILLS[i % 4].id;
    out.push(makeQuestion(skill, makeLaunch(seed * 31 + i), i));
  }
  return out;
}

/** Strip LaTeX to readable plain text for the answer key. */
function plain(tex: string): string {
  return tex
    .replace(/\\dfrac\{([^{}]*(?:\{[^{}]*\}[^{}]*)*)\}\{([^{}]*)\}/g, "($1) / ($2)")
    .replace(/\\tfrac12/g, "½")
    .replace(/\\sqrt\{([^{}]*)\}/g, "sqrt($1)")
    .replace(/\\text\{\s*([^}]*)\}/g, "$1")
    .replace(/\\(quad|qquad|,|;|!)/g, " ")
    .replace(/\\ /g, " ")
    .replace(/\\times/g, "×")
    .replace(/\\cos/g, "cos")
    .replace(/\\sin/g, "sin")
    .replace(/\\theta/g, " angle")
    .replace(/\\max/g, "max")
    .replace(/\^\\circ/g, "°")
    .replace(/\^2/g, "²")
    .replace(/_\{([^}]*)\}/g, "$1")
    .replace(/_(\w)/g, "$1")
    .replace(/\\Delta /g, "change in ")
    .replace(/\\Delta/g, "change in ")
    .replace(/[{}]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function diagram(doc: jsPDF, x: number, y: number, w: number, h: number, l: Launch) {
  // Schematic: cliff, sea, cannon and launch angle.
  doc.setDrawColor(40);
  doc.setLineWidth(0.4);
  const cliffW = w * 0.22;
  const seaY = y + h;
  const topY = y + h * 0.35;
  doc.setFillColor(225, 221, 212);
  doc.rect(x, topY, cliffW, seaY - topY, "FD");
  doc.setDrawColor(90, 130, 160);
  for (let i = 0; i < 3; i++) doc.line(x + cliffW, seaY + i * 1.6, x + w, seaY + i * 1.6);
  doc.setDrawColor(40);
  const ang = (l.angleDeg * Math.PI) / 180;
  // Barrel resting on the clifftop, muzzle up at the launch angle.
  const bx = x + cliffW - 8;
  const by = topY - 1.2;
  const mx = bx + 7 * Math.cos(ang);
  const my = by - 7 * Math.sin(ang);
  doc.setLineWidth(1.4);
  doc.line(bx, by, mx, my);
  doc.setFillColor(60, 60, 60);
  doc.circle(bx + 1, topY - 0.9, 0.9, "F");
  doc.setLineWidth(0.3);
  doc.setLineDashPattern([1, 1], 0);
  doc.line(mx, my, mx + 16, my);
  doc.setLineDashPattern([], 0);
  doc.setFontSize(8);
  doc.text(`${l.angleDeg}°`, mx + 9, my - 2);
  const { vx: ax, vy: ay } = components(l);
  const k = 0.55;
  doc.text(`${l.v0} m/s`, mx + ax * k + 1.5, my - ay * k + 1);
  // Height marker
  doc.line(x - 3, topY, x - 3, seaY);
  doc.text(`${l.h} m`, x - 4, (topY + seaY) / 2, { angle: 90 });
  doc.setDrawColor(200, 120, 60);
  doc.line(mx, my, mx + ax * k, my - ay * k);
  doc.setDrawColor(40);
}

export function buildWorksheet(seed: number): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const qs = worksheetQuestions(seed);
  const margin = 18;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Projectile motion: two motions at once", margin, 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text(
    "Name ______________________________     Date ______________     Take g = 9.8 m/s². Ignore air resistance.",
    margin,
    32,
  );
  doc.setDrawColor(180);
  doc.line(margin, 36, 210 - margin, 36);

  let y = 44;
  qs.forEach((q, i) => {
    if (y > 252) {
      doc.addPage();
      y = 24;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text(`${i + 1}.`, margin, y + 4);
    doc.setFont("helvetica", "normal");
    const lines = doc.splitTextToSize(q.prompt, 105);
    doc.text(lines, margin + 7, y + 4);
    diagram(doc, 150, y, 40, 26, q.launch);
    doc.setFontSize(9);
    doc.setTextColor(110);
    doc.text(`Answer (${q.unit}): ____________`, margin + 7, y + 34);
    doc.setTextColor(0);
    doc.setDrawColor(230);
    for (let k = 0; k < 3; k++) doc.line(margin + 7, y + 14 + k * 6, 140, y + 14 + k * 6);
    y += 41;
  });

  doc.addPage();
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Answer key", margin, 24);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  y = 34;
  qs.forEach((q, i) => {
    doc.setFont("helvetica", "bold");
    doc.text(`${i + 1}. ${q.answer.toFixed(q.unit === "s" ? 2 : 1)} ${q.unit}`, margin, y);
    doc.setFont("helvetica", "normal");
    const work = q.steps.map(plain).join("   >   ");
    const lines = doc.splitTextToSize(work, 210 - margin * 2 - 8);
    doc.text(lines, margin + 8, y + 6);
    y += 10 + lines.length * 5;
  });
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text(`Worksheet ${seed} · generated by the Physics Lab Showcase`, margin, 287);
  return doc;
}

export async function offerWorksheet(seed: number): Promise<string> {
  const doc = buildWorksheet(seed);
  const blob = doc.output("blob");
  const filename = `projectile-worksheet-${seed}.pdf`;
  const claude = (window as unknown as { claude?: { use: (n: string) => Promise<unknown> } })
    .claude;
  const downloads = (await claude?.use("downloads")) as
    | { save: (r: { filename: string; data: Blob }) => Promise<unknown> }
    | null
    | undefined;
  if (downloads) {
    try {
      await downloads.save({ filename, data: blob });
      return "Saved.";
    } catch (e) {
      const code = (e as { code?: string }).code;
      return code === "declined" ? "Download cancelled." : "Downloads aren't available here.";
    }
  }
  // Outside claude.ai (e.g. running the app locally) a normal download link works.
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  setTimeout(() => URL.revokeObjectURL(a.href), 4000);
  return "Downloaded.";
}

// Lets the printables script fetch the PDF bytes.
(window as unknown as { __worksheetBase64?: (seed: number) => string }).__worksheetBase64 = (
  seed: number,
) => buildWorksheet(seed).output("datauristring").split(",")[1];
